collections:
  - name: redhat.insights
    version: 1.0.5
  - name: chocolatey.chocolatey
    version: 1.0.2
  - name: ansible.windows
    version: 1.7.3
  - name: community.windows
    version: 1.7.0
  - name: community.general
    version: 3.7.0
  - name: ansible.posix
    version: 1.3.0
  - name: splunk.es
    version: 1.0.2
  - name: redhat.rhv
    version: 1.6.2
  - name: shadowman.reports
    source: https://github.com/michaelford85/shadowman.reports.git


  